fix: correct types for some customization options
progfolio/elpaca pull request #103
Opened 2023-04-18 20:57 UTC by lebensterben

2023-04-18 23:24 UTC, progfolio requested changes

2023-04-18 23:24 UTC, progfolio commented on elpaca.el
> +                :value-type face))
Unfortunatley this throws an error for me on Emacs 30 and 27:

0. apply patch
1. `M-x customize-group` `elpaca`
2.  Click the "Show value" button (or arrow depending on Emacs version) to the left of Elpaca Status Faces in the Customize Group: Elpaca buffer.

Expected behavior: The value options are shown.
Actual behavior: An error is signaled (see below) and the widget is removed from the buffer.

<details><summary>error backtrace</summary>

```emacs-lisp
Debugger entered--Lisp error: (void-function nil)
  nil((:options :args ((blocked finished failed busy))) blocked)
  widget-match-inline((:options :args ((blocked finished failed busy))) (blocked elpaca-blocked))
  widget-group-match-inline((cons :format "%v" :args ((:options :args ((blocked finished failed busy))) (face :value "default"))) (blocked elpaca-blocked))
  widget-group-match((cons :format "%v" :args ((:options :args ((blocked finished failed busy))) (face :value "default"))) (blocked elpaca-blocked))
  widget-cons-match((cons :format "%v" :args ((:options :args ((blocked finished failed busy))) (face :value "default"))) (blocked . elpaca-blocked))
  widget-match-inline((cons :format "%v" :args ((:options :args ((blocked finished failed busy))) (face :value "default"))) ((blocked . elpaca-blocked) (finished . elpaca-finished) (failed . elpaca-failed) (busy . elpaca-busy)))
  widget-editable-list-match-inline((editable-list :inline t :args ((cons :format "%v" :args ((:options :args ((blocked finished failed busy))) (face :value "default"))))) ((blocked . elpaca-blocked) (finished . elpaca-finished) (failed . elpaca-failed) (busy . elpaca-busy)))
  widget-match-inline((editable-list :inline t :args ((cons :format "%v" :args ((:options :args ((blocked finished failed busy))) (face :value "default"))))) ((blocked . elpaca-blocked) (finished . elpaca-finished) (failed . elpaca-failed) (busy . elpaca-busy)))
  widget-group-match-inline((alist :key-type (:options (blocked finished failed busy)) :value-type face :args ((editable-list :inline t :args ((cons :format "%v" :args ((:options :args ...) (face :value "default"))))))) ((blocked . elpaca-blocked) (finished . elpaca-finished) (failed . elpaca-failed) (busy . elpaca-busy)))
  widget-group-match((alist :key-type (:options (blocked finished failed busy)) :value-type face :args ((editable-list :inline t :args ((cons :format "%v" :args ((:options :args ...) (face :value "default"))))))) ((blocked . elpaca-blocked) (finished . elpaca-finished) (failed . elpaca-failed) (busy . elpaca-busy)))
  custom-variable-value-create((custom-variable :group ... :tag ... :custom-prefixes ... :custom-level 2 :value elpaca-status-faces :parent ... :indent ...))
  widget-default-create((custom-variable :group ... :tag ... :custom-prefixes ... :custom-level 2 :value elpaca-status-faces :parent ... :indent ...))
  widget-default-value-set((custom-variable :group ... :tag ... :custom-prefixes ... :custom-level 2 :value elpaca-status-faces :parent ... :indent ...) elpaca-status-faces)
  widget-value-set((custom-variable :group ... :tag ... :custom-prefixes ... :custom-level 2 :value elpaca-status-faces :parent ... :indent ...) elpaca-status-faces)
  custom-redraw((custom-variable :group ... :tag ... :custom-prefixes ... :custom-level 2 :value elpaca-status-faces :parent ... :indent ...))
  custom-toggle-hide-variable((custom-visibility :args nil :value nil :help-echo "Show the value..." :on-glyph "down" :on "Hide" :off-glyph "right" :off ...) nil)
  widget-apply-action((custom-visibility :args nil :value nil :help-echo "Show the value..." :on-glyph "down" :on "Hide" :off-glyph "right" :off ...) nil)
  Custom-newline(2283)
  funcall-interactively(Custom-newline 2283)
  command-execute(Custom-newline)
```


</details>


Does this type spec allow for adding arbitrary `(status . face)` cells in addition to the listed `:options`? Users (and third party packages) may want to augment the list with their own options.

2023-04-18 23:24 UTC, progfolio commented on elpaca.el
> +  "Path of the install-info executable." :type '(file :must-match))
Should there be a `t` value for `:must-match` here as well?
That is the only value I see documented in the manual.

2023-04-19 04:32 UTC, lebensterben commented on elpaca.el
> +                :value-type face))
Unfortunately I cannot reproduce this error on 28.2.

![2023-04-19-002443_2560x1440_scrot](https://user-images.githubusercontent.com/1222865/232967646-9e14cbdb-ca68-4a5b-be63-c9b536cfd9cf.png)

2023-04-19 18:03 UTC, progfolio commented on elpaca.el
> +                :value-type face))
I'm able to reproduce on 28.2. I tested on 27 and 28 via a docker image w terminal Emacs and
30 on my personal machine (linux) with GUI and terminal.
Same issue on all three for me. I'd say it'd be better to exclude this change for now until someone can figure out how to make it work for all of those.
I'd be happy to accept the other changes.

2023-04-19 22:30 UTC, lebensterben commented on elpaca.el
> +                :value-type face))
@progfolio 

After `elpaca-rebuild`, I'm able to reproduce this error.
I've pushed the fix.

2023-04-20 01:19 UTC, progfolio commented on elpaca.el
> +                :value-type face))
```suggestion
  :type '(alist :key-type symbol :options '(blocked finished failed busy) :value-type face))
```

From the elisp manual section on "Composite Types":

>     The argument to the ‘:options’ keywords should be a list of
     specifications for reasonable keys in the alist.  Ordinarily, they
     are simply atoms, which stand for themselves.  For example:

          :options '("foo" "bar" "baz")

That should provide properly labeled checkbox widgets:
![image](https://user-images.githubusercontent.com/44036031/233233216-e47d46b0-433a-4798-aaa9-d68fe8fdf7ba.png)

2023-04-20 02:23 UTC, lebensterben commented
@progfolio I committed your suggestion.

2023-04-20 02:24 UTC, progfolio commented on elpaca.el
> +" t)))
Unrelated changes?

2023-04-20 02:26 UTC, progfolio commented on elpaca.el
> +" t)))
Here, too

2023-04-20 02:39 UTC, lebensterben commented on elpaca.el
> +" t)))
That's strange. It doesn't show up on my local. And 

git diff [f53b8c](https://github.com/lebensterben/elpaca/commit/f53b8c25533b79878cca20420e29a03163b2ed9b)

shows nothing

2023-04-20 02:41 UTC, progfolio commented on elpaca.el
> +" t)))
Interesting. Git configured to ignore white space changes maybe?

2023-04-20 02:43 UTC, lebensterben commented
It's strange.
I manually replaced the redundant newline with "^M".

But now it shows that "^M" and "^M" are different.

2023-04-20 02:43 UTC, lebensterben commented on elpaca.el
> +         (returnp (string-match-p "^M" chunk))
I've no idea what's going on here.

2023-04-20 02:45 UTC, progfolio commented on elpaca.el
> +         (returnp (string-match-p "^M" chunk))
>  I manually replaced the redundant newline with "^M".

Won't work by typing "^" followed by "M". The original value was a control character for a return.
You'll have to type `C-q` followed by `RET`.

2023-04-20 02:46 UTC, lebensterben commented on elpaca.el
> +         (returnp (string-match-p "^M" chunk))
It's fixed now.

2023-04-20 02:46 UTC, lebensterben commented
This is a bug caused by parinfer-rust-mode.

2023-04-20 02:54 UTC, merged

2023-04-20 02:54 UTC, lebensterben commented
Given that
- It confuses parinfer-rust-mode
- It confuses git-diff
- It appears as a string `"^M"` on github.com web interface but as a zero-width whitespace on github ios client.

Should we use "\n" instead?

2023-04-20 02:55 UTC, progfolio commented
Merged! Thank you.

2023-04-20 03:07 UTC, progfolio commented
> Given that
> 
>     * It confuses parinfer-rust-mode
> 
>     * It confuses git-diff
> 
>     * It appears as a string `"^M"` on github.com web interface but as a zero-width whitespace on github ios client.
> 
> 
> Should we use "\r" instead?

That should work. I've patched that as well.