Consider ELPA's manual-sync repositories as a developed in ELPA
progfolio/elpaca pull request #340
Opened 2024-08-14 14:05 UTC by jtamagnan

# Foreword

I hope this pull-request finds you well. Thank you for all of the time
and support on my previous issues. I continued looking into some
issues I encountered and figured that I could perhaps propose an
improvement.

I'm unsure what the longterm plans are with this package but I do have
signed FSF papers in case that is a requirement for contribution.

# Background

There are many Elpa packages that when downloaded through package.el
have different content compared to when they are downloaded through
Elpaca. An example of this is the [chess package](https://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/elpa-packages?h=main#n145) or the [bbdb package](https://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/elpa-packages?h=main#n89).

Looking at these packages we can see that they use the `manual-sync t`
setting.  This setting in `elpa-packages` indicates that the package
is actually manually synced into the Elpa repository and that the
"source of truth" is in Elpa and not the remote repository. When
Elpa builds a tarball for such a package it uses the Elpa repository
not the remote repository.

It seems like the main reasons for the existence of this flag can be seen
in a comment in the chess recipe:
```
;; FIXME: The two versions are badly out of sync.
```
This flag allows Elpa developers to maintain a package in the Elpa
repository while still keeping a reference to the upstream.

# Problem

Elpaca does not handle these manual-sync packages in the same way as
Elpa expects them to be handled. Elpaca ignores the `manual-sync t`
setting and downloads the package from the upstream repository. This
is a problem because Elpaca downloads a different package than Elpa
intends to expose.

# Solution

If an Elpa package uses `manual-sync t` Elpaca should install it from
the relevant branch in the Elpa repository instead of from the
upstream.

# Implementation

I modified the `elpaca-menu-elpa--index` to handle this `manual-sync`
setting and choose a different URL in that case.

# Testing

To test that this works correctly I figured I would look at a recipe
before and after my change. Note that I've also tested that installing
works properly but that isn't very relevant since I haven't changed
anything there.

The most minimal test I could come up with was to look at the recipe:
```elisp
(prog1
    (let ((elpaca-menu-functions '(elpaca-menu-gnu-devel-elpa)))
      (elpaca-update-menus)
      (elpaca-recipe 'chess))
  (elpaca-update-menus))
```  

**Before my change**:
```
(:package "chess" 
 :repo "https://github.com/jwiegley/emacs-chess.git" 
 :local-repo "chess" 
 :files ("*" (:exclude ".git")) 
 :source "GNU-devel ELPA" 
 :protocol https ...)
```

**After my change**: 
```
(:package "chess" 
 :repo "git://git.sv.gnu.org/emacs/elpa" 
 :local-repo "chess" 
 :branch "externals/chess" 
 :files ("*" (:exclude ".git")) 
 :source "GNU-devel ELPA" ...)
```

We can see that after my change the intended branch is selected

2024-08-14 15:24 UTC, progfolio requested changes
> I hope this pull-request finds you well. Thank you for all of the time
and support on my previous issues.

Thank you for the kind words and your patch!

> I'm unsure what the longterm plans are with this package but I do have
signed FSF papers in case that is a requirement for contribution.

I appreciate the forward thinking on your part here.
Currently I don't have any plans to upstream Elpaca into Emacs, so FSF copyright assignment is not a requirement for contribution.
Good to know in case that changes, though.

Thank  you for the thorough explanation of the motivation for this change.
Makes perfect sense to me.

> The most minimal test I could come up with was to look at the recipe:

Careful, `elpaca-update-menus` will overwrite your `$ELPACA-CACHE-DIR/menu-items.eld` file. You can work around this by also let-binding `elpaca-cache-directory` to a temp directory. An even safer way to do this is to use the `elpaca-test` macro, as below:

<!-- copy buffer contents to issue comment or new issue -->
<details open><summary>Test Case</summary>

[How to run this test?](https://github.com/progfolio/elpaca/wiki/Troubleshooting#the-elpaca-test-macro)

```emacs-lisp
(elpaca-test
  :early-init
  (setq elpaca-menu-functions '(elpaca-menu-gnu-devel-elpa)
        elpaca-order '(elpaca :repo "https://github.com/jtamagnan/elpaca.git"
                              :ref nil :depth 1
                              :files (:defaults "elpaca-test.el" (:exclude "extensions"))
                              :build (:not elpaca--activate-package)))
  :init
  (princ (elpaca-info 'chess)))
```

</details>
<details><summary>Host Env</summary>

<table>
<tr><td>elpaca</td><td>ff23a69 HEAD -> simple-lockfile, origin/simple-lockfile</td>
<tr><td>installer</td><td>0.7</td>
<tr><td>emacs</td><td>GNU Emacs 31.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.43, cairo version 1.18.0) of 2024-08-12</td>
<tr><td>git</td><td>git version 2.46.0</td>
</table>
</details>

<details><summary>Output</summary>

```emacs-lisp
Elpaca menu item cache discarded due to version change.
  INFO     Scraping 16 files for loaddefs... 
  INFO     Scraping 16 files for loaddefs...done
  GEN      ../elpaca-autoloads.el
Cloning into '/tmp/elpaca.NMXznP/elpaca/repos/elpaca'...
Your branch is up to date with 'origin/master'.
Checking /tmp/elpaca.NMXznP/elpaca/repos/elpaca...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/elpaca-info.el...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/elpaca-log.el...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/elpaca-manager.el...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/elpaca-menu-elpa.el...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/elpaca-menu-melpa.el...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/elpaca-menu-org.el...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/elpaca-process.el...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/elpaca-test.el...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/elpaca-ui.el...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/elpaca.el...
Checking /tmp/elpaca.NMXznP/elpaca/repos/elpaca/doc...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/doc/early-init.el...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/doc/init.el...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/doc/installer.el...
Checking /tmp/elpaca.NMXznP/elpaca/repos/elpaca/extensions...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/extensions/elpaca-use-package.el...
Checking /tmp/elpaca.NMXznP/elpaca/repos/elpaca/images...
Checking /tmp/elpaca.NMXznP/elpaca/repos/elpaca/test...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/test/elpaca-test.el...
Compiling /tmp/elpaca.NMXznP/elpaca/repos/elpaca/test/elpaca-tests.el...
Done (Total of 12 files compiled, 4 skipped in 4 directories)

Downloading GNU-devel ELPA...
chess
Play chess in GNU Emacs

source: GNU-devel ELPA
url: https://elpa.gnu.org/packages/chess.html
menu item recipe:
( :package "chess"
  :repo "git://git.sv.gnu.org/emacs/elpa"
  :local-repo "chess"
  :branch "externals/chess"
  :files ("*" (:exclude ".git")))
full recipe:
( :package "chess"
  ;; Inherited from elpaca-order-functions.
  :depth 1
  :inherit t
  :protocol https
  ;; Inherited from elpaca-menu-item.
  :files ("*" (:exclude ".git"))
  :branch "externals/chess"
  :local-repo "chess"
  :repo "git://git.sv.gnu.org/emacs/elpa")
dependencies:
?
dependents: ?
```
</details>


I left comment about how we can simplify the change. Let me know what you think.

2024-08-14 15:24 UTC, progfolio commented on elpaca-menu-elpa.el
> +   for manual-sync = (plist-get props :manual-sync)
I don't think we need to cache the :manual-sync property, considering we only use it once per item.

```suggestion
```

2024-08-14 15:24 UTC, progfolio commented on elpaca-menu-elpa.el
> +                 (and manual-sync remote)
```suggestion
                 (and (plist-get props :manual-sync) remote) ;; developed in ELPA repo
```

2024-08-14 16:15 UTC, jtamagnan commented
Thank you for the super quick response and suggested improvements. I've committed those and tested them again. It seems good to go.

---

> Careful, elpaca-update-menus will overwrite your $ELPACA-CACHE-DIR/menu-items.eld file. You can work around this by also let-binding elpaca-cache-directory to a temp directory. An even safer way to do this is to use the elpaca-test macro, as below:

Ahhh yeah, I had tried to use `elpaca-test` but I missed the use of `elpaca-order`. I was trying to test my local changes so was using `:ref local` but ran into issues when that continued to use my cache directory. I was hoping to be able to set `:ref` to a local git commit but ran into some issues with `elpaca-test--upstream-init`, it seems like `:ref` needs to point to an upstream version of Elpaca. I'll continue experimenting with `elpaca-test` to see if I can figure out a good workflow for testing my local changes without needing to push to GitHub first; maybe `:ref` can be enhanced to support this. To this point I've found `elpaca-test` really helpful for creating test cases against the main branch but not for active development.

One thing is that it seems like `elpaca-test--upstream-format` is hardcoded regardless of the `elpaca-order`.

2024-08-15 10:29 UTC, merged

2024-08-15 10:35 UTC, progfolio commented
> Thank you for the super quick response and suggested improvements. I've committed those and tested them again. It seems good to go.

Merged. Thank you.

There are definitely ways we could improve the `elpaca-test` macro.
Ideas and patches are always welcome.

> One thing is that it seems like elpaca-test--upstream-format is hardcoded regardless of the elpaca-order.

I have a TODO note about fixing this. I'll take a look at it when I have time.

Thanks again.