Make tags work reliably as version info
progfolio/elpaca pull request #359
Opened 2024-09-20 17:50 UTC by meedstrom

This PR works in my testing of one package. How I tested it:

- Made org-node-fakeroam depend on org-node "0.10"
- Tag "0.10" is NOT the latest commit in org-node
- My checkouts of both packages are shallow, containing only one commit
- It could still install successfully! It used to complain "version 0 lower than min required".

2024-09-23 09:25 UTC, meedstrom commented
I'll add that currently the latest commit in org-node is now tagged, which makes testing this PR difficult. I'll add a branch without a tag in case that helps.

    (elpaca (org-node :fetcher github :repo "meedstrom/org-node" :branch "with-untagged-head"))

2024-09-23 12:50 UTC, progfolio requested changes
This will definitely need more testing than a single package.

How does this method guarantee that the remote tag includes the ref which is locally checked out? At a glance it looks like it will always report the latest tag regardless of local state. That will lead to the incorrect version being reported.

2024-09-23 12:50 UTC, progfolio commented on elpaca.el
> +      eos))
I'd like to avoid loading `rx`. My goal is to keep Elpaca's dependencies minimal, because eventually users want to install those same dependencies. If they are loaded by Elpaca it makes it much trickier for them than it needs to be.

2024-09-23 12:50 UTC, progfolio commented on elpaca.el
> +                       "origin")
Cannot hard code the name "origin" here.
The correct remote name would need to derived from the recipe.

2024-09-23 12:57 UTC, meedstrom commented on elpaca.el
> +      eos))
I understand, so you can just replace this with the evalled result. I thought this might help you refine the regexp if you want first. 

By the way, rx is built-in to Emacs and a macro, so elpaca.elc would not need to load it at runtime.  It'd be the same what you do with subr-x and cl-lib, I believe.

2024-09-23 12:59 UTC, meedstrom commented on elpaca.el
> +      eos))
Actually it is autoloaded, so I believe a `require` statement` is not even needed.

2024-09-23 13:07 UTC, meedstrom commented on elpaca.el
> +      eos))
Agreed, that's a nice goal, although `rx` is not even an ELPA package... but anyway, correct me here, if there is no top-level `(require 'rx`)` in the file, and the only thing used from that library is a macro, then the compiler expands that into a regexp string at compile time and then elpaca.elc only contains that string and no rx code at all that would even trigger an autoload.

2024-09-23 13:11 UTC, progfolio commented on elpaca.el
> +      eos))
Apologies. Very little time. Before diving into implementation details, please address this:

https://github.com/progfolio/elpaca/pull/359#pullrequestreview-2322022987

2024-09-23 13:12 UTC, meedstrom commented on elpaca.el
> +      eos))
No problem. I will.

2024-09-23 20:26 UTC, meedstrom commented
I believe I have a good solution. Imagine a situation:

1. first-time install: Elpaca does shallow clone of "main". Call that commit X.
2. user immediately makes a new branch "dev" and makes commits
4. user switches to "main" and makes commits, finally tagging a commit as 0.8.4
5. user switches back to "dev"
6. user pushes both branches to the remote (and forgets to push tags, which will be relevant in a minute)

In this situation, we can still be certain that HEAD has a history that traces back to commit X, which is in the history of "main" as well as "dev". However, tag 0.8.4 should be ignored since it is not in the history for "dev".

So what we do is we rule out all `git tag --no-merged` tags. This drops 0.8.4 from the candidates.

And on the remote, we rule out all tags not reachable from commit X. This drops tags that only exist on other branches.

It *could* happen that the remote actually already had a reachable tag 0.8.4, and now we dropped it, but that would be an user mistake because they added a tag locally that already existed on the remote.  In my opinion, not worth accounting for.  They would soon find out the problem when they try to push the tag, and in some way, it can even be regarded a bonus that Elpaca would potentially provide an extra-early warning by emitting a "too low version" error (to which the user would very likely react by attempting to push tags).

...

...

... 

Or that was the plan.

It does not seem like `git ls-remote` has a way to filter by reachability. There is an `-o` / `--server-options` flag which maybe could do the trick, but I believe I've found a more principled approach.

Have you ever heard of treeless or blobless clones? If not, I found this an instructive article: https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/

If you did already consider them and reject them, let me know.

It's a relatively new way to do shallow clones.

They speak of four ways to clone, in decreasing order of "completeness":

1. Full clone
2. Blobless clone
3. Treeless clone (which also implies blobless)
4. Shallow clone (which also implies treeless and blobless)

And they say so much about treeless clones being nasty and unpredictable, because they are coming at it from the perspective of blobless. But all the disadvantages of treeless, a shallow clone has too, so from our perspective even a treeless clone would be a pure upgrade in functionality. Except for that thing they said about submodules.

Maybe I should leave at that and let you form your own impressions. You've probably already understood that treeless would allow us to just reuse the original design you had in `elpaca-latest-tag` with no changes. 

Download sizes for my package org-node:

- `git clone --depth=1` -> sum 93 KiB
- `git clone --filter=tree:0` -> sum 215 KiB
- `git clone --filter=blob:none` -> sum 269 KiB
- `git clone` -> 2.88 MiB

2024-09-24 01:51 UTC, progfolio commented
> Have you ever heard of treeless or blobless clones?

I mentioned them as an option I was considering to you a few days ago:
https://github.com/progfolio/elpaca/issues/353#issuecomment-2358860518

2024-09-24 09:45 UTC, meedstrom commented
Ah, somehow that didn't register. Sorry for not reading you properly. Well, then my opinion is that it looks like the most convenient solution for users, developers as well as elpaca's own code complexity.  

Is it just a matter of amending `elpaca--clone`? I'll try, and re-download all packages, and see if anything breaks.

2024-09-26 17:18 UTC, progfolio commented
> Ah, somehow that didn't register. Sorry for not reading you properly. Well, then my opinion is that it looks like the most convenient solution for users, developers as well as elpaca's own code complexity.
> 
> Is it just a matter of amending `elpaca--clone`? And `elpaca--initial-fetch`. I'll try, and re-download all packages, and see if anything breaks.

I've added support for `:depth` `treeless` (the new default) and `blobless` on the master branch.
See how that works after an `M-x elpaca-update` `elpaca` followed by `M-x restart-emacs`.
Testing is appreciated. Thanks.

2024-09-26 17:22 UTC, closed without merging

2024-09-26 18:49 UTC, meedstrom commented
Works without any obvious issues so far! I re-cloned every package too. I appreciate how I can see the commit logs of every package now, it's a nice bonus.

Another bonus: I can see all branches on the origin. Guessing I used to do something wrong but I used to have to configure a new remote "meedstrom" for the same url as "origin", to get to see the other branches, but I never got around to figuring it out.

Another bonus: I can now install sisyphus without special configuration, fixing https://github.com/tarsius/llama/issues/2.

Thank you!

2024-09-26 19:27 UTC, progfolio commented
Thanks for testing.

2024-09-26 19:37 UTC, progfolio commented
By the way:

I'm not necessarily opposed to this change:
https://github.com/progfolio/elpaca/pull/359/commits/ede6f88b996665ceb51befea026e21734c0f645e

It would just need to be separated out from the rest.

2024-09-26 21:13 UTC, meedstrom commented
Do you want it in rx or string form? :)

2024-09-26 21:24 UTC, progfolio commented
String for now
-------- Original message --------From: Martin Edström ***@***.***> Date: 9/26/24  5:14 PM  (GMT-05:00) To: progfolio/elpaca ***@***.***> Cc: Nicholas Vollmer ***@***.***>, State change ***@***.***> Subject: Re: [progfolio/elpaca] Make tags work reliably as version info (PR #359) 
Do you want it in rx or string form? :)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>