Mostly sync with MELPA :version-regexp
progfolio/elpaca pull request #364
Opened 2024-09-26 21:38 UTC by meedstrom

This regexp differs slightly from MELPA's version because it excludes %p, where they would substitute the package name, enabling tags like "elpaca-0.2" if the package is named elpaca.

If you want, I can sub it in with some `(plist-get recipe ...)`. But maybe this forms a sort of natural boundary, for how smart the version inference should be in the first place. It's convenient to keep it self-contained in the regexp.

2024-09-26 21:55 UTC, meedstrom commented
While it does not affect this PR right now, I saw something possibly concerning. Does elpaca generally handle %v and %p in custom version regexps such as these?

https://github.com/melpa/melpa/commit/f9103b6c58996e75c0e5c23fc0fb12afd65424c0

For reference, the transformations seem to be done by the function `package-build--version-regexp` at https://github.com/melpa/package-build/blob/master/package-build.el

2024-09-27 00:10 UTC, progfolio requested changes

2024-09-27 00:10 UTC, progfolio commented on elpaca.el
> +;; See `package-build-version-regexp' in https://github.com/melpa/melpa/blob/c84e975e5cd3ff264a134e4608041947ef010f01/package-build/package-build.el#L250
```suggestion
```

2024-09-27 00:18 UTC, progfolio commented
> This regexp differs slightly from MELPA's version

That's fine. I'm not interested in strict MELPA compatibility.

> Let me know if you want me to remove the comment line.

Yes please.


> Custom regexps can apparently have %v and %p, examples seen in melpa/melpa@f9103b6
> Not sure if elpaca handles that yet?

Nope. That would be something to add to elpaca-menu-melpa.el, if at all.

> it would've made more sense to me if Melpa just limited the set of permissible tag formats and made it non-customizable

IMO semver should be the only scheme, but it's too late for that.

2024-09-27 12:24 UTC, meedstrom commented
Done.

2024-09-30 02:10 UTC, progfolio approved these changes

2024-09-30 02:13 UTC, merged

2024-09-30 02:14 UTC, progfolio commented
Merged. Thanks.

2024-10-01 02:31 UTC, jinzhongjia commented
This PR seems to have caused new problems?
![image](https://github.com/user-attachments/assets/985e1014-3e3a-4fcc-95ce-cdbe7987ac11)
It will always be blocked here

2024-10-01 02:40 UTC, jinzhongjia commented
I forked elpaca and tried to roll back to the previous commit, but it was still blocked.

2024-10-01 03:12 UTC, jinzhongjia commented
Sorry, please ignore the above statement, it seems to be my network problem

2024-10-01 10:57 UTC, progfolio commented
@jinzhongjia please read this prior to requesting support:

https://github.com/progfolio/elpaca/wiki/Troubleshooting

These sections in particular:

https://github.com/progfolio/elpaca/wiki/Troubleshooting#check-your-network-connection
https://github.com/progfolio/elpaca/wiki/Troubleshooting#prefer-text-over-screenshots

Thanks

2024-10-01 14:22 UTC, jinzhongjia commented
> @jinzhongjia please read this prior to requesting support:
> 
> [Wiki: Troubleshooting](https://github.com/progfolio/elpaca/wiki/Troubleshooting)
> 
> These sections in particular:
> 
> [Wiki: Troubleshooting (check your network connection)](https://github.com/progfolio/elpaca/wiki/Troubleshooting#check-your-network-connection) [Wiki: Troubleshooting (prefer text over screenshots)](https://github.com/progfolio/elpaca/wiki/Troubleshooting#prefer-text-over-screenshots)
> 
> Thanks

No intention to disturb, but I need to explain that the above blocking problem is because gnu cannot be accessed for several hours in the past, which has resulted in constant blocking.